# docker-compose-prom.yml
# docker-compose -f docker-compose-prom.yaml up -d
version: '2' 

  
services: 
    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
        networks:
           - byfn
    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter:latest
        ports:
            - '9100:9100'
        networks:
           - byfn

    cadvisor:
        image: google/cadvisor:latest
        container_name: monitoring_cadvisor
        restart: unless-stopped
        volumes:
           - /:/rootfs:ro
           - /var/run:/var/run:rw
           - /sys:/sys:ro
           - /var/lib/docker/:/var/lib/docker:ro
        ports:
           - '8080:8080'
        networks:
           - byfn
           
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        depends_on:
            - prometheus
        volumes:
            - grafana_data:/var/lib/grafana
        ports:
            - "3000:3000"
        networks:
            - byfn
      
volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
    byfn: