# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    # static_configs:
      # - targets: ['192.168.1.200:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
###########################Fabric##########################
  - job_name: 'Orderer0'
    static_configs:
      - targets: ['orderer.example.com:8443']
  - job_name: 'Orderer2'
    static_configs:
      - targets: ['orderer2.example.com:8443']
  - job_name: 'Orderer3'
    static_configs:
      - targets: ['orderer3.example.com:8443']
  - job_name: 'Orderer4'
    static_configs:
      - targets: ['orderer4.example.com:8443']
  - job_name: 'Orderer5'
    static_configs:
      - targets: ['orderer5.example.com:8443']
  - job_name: 'peer0_org1'
    static_configs:
      - targets: ['peer0.org1.example.com:9443']
  - job_name: 'peer1_org1'
    static_configs:
      - targets: ['peer1.org1.example.com:9443']
  - job_name: 'peer0_org2'
    static_configs:
      - targets: ['peer0.org2.example.com:9443']
  - job_name: 'peer1_org2'
    static_configs:
      - targets: ['peer1.org2.example.com:9443']
